export {
  type ShadowConfig,
  type ShadowTrade,
  type ShadowMetrics,
  type ShadowSession,
  type ShadowComparison,
  type ShadowStatTest,
  createShadowSession,
  recordShadowTrade,
  completeShadowSession,
  pauseShadowSession,
  resumeShadowSession,
  abortShadowSession,
  getShadowSession,
  getActiveSessions,
  getAllSessions,
  getSessionsByStrategy,
  compareShadowToLive,
  runStatisticalTest,
  _clearShadowTrading,
} from "./shadow_executor";
