import { Router, type IRouter } from "express";
import healthRouter from "./health";
import signalsRouter from "./signals";
import tradesRouter from "./trades";
import performanceRouter from "./performance";
import systemRouter from "./system";
import alpacaRouter from "./alpaca";
import orderbookRouter from "./orderbook";
import strictSetupRouter from "./strict_setup";
import researchRouter from "./research";
import brainRouter from "./brain";
import superIntelligenceRouter from "./super_intelligence";
import backtestRouter from "./backtest";
import paperValidationRouter from "./paper_validation";
import alertsRouter from "./alerts";
import checklistRouter from "./checklist";
import warRoomRouter from "./war_room";
import proofRouter from "./proof";
import macroRouter from "./macro";
import journalRouter from "./journal";
import watchlistRouter from "./watchlist";
import analyticsRouter from "./analytics";
import portfolioRouter from "./portfolio";
import opsRouter from "./ops";
import featuresRouter from "./features";
import engineHealthRouter from "./engine_health";
import executionRouter from "./execution";
import sessionsRouter from "./sessions";
import streamingRouter from "./streaming";
import deploymentReadinessRouter from "./deployment_readiness";
import autonomyDebuggerRouter from "./autonomy_debugger";
import autonomyDebugSchedulerRouter from "./autonomy_debug_scheduler";
import autonomySupervisorRouter from "./autonomy_supervisor";
import strategyGovernorRouter from "./strategy_governor";
import strategyAllocatorRouter from "./strategy_allocator";
import strategyEvolutionRouter from "./strategy_evolution";
import productionWatchdogRouter from "./production_watchdog";
import executionSafetySupervisorRouter from "./execution_safety_supervisor";
import leaderboardRouter from "./leaderboard";
import pythonV2Router from "./python_v2";
import brainNodesRouter from "./brain_nodes";
import portfolioAllocatorRouter from "./portfolio_allocator";
import decisionReplayRouter from "./decision_replay";
import microstructureRouter from "./microstructure";
import contextFusionRouter from "./context_fusion";
import adaptiveLearningRouter from "./adaptive_learning";
import executionIntelligenceRouter from "./execution_intelligence";
import strategyRegistryRouter from "./strategy_registry";
import godsviewLabRouter from "./godsview_lab";
import walkForwardStressRouter from "./walk_forward_stress";
import tradingviewOverlayRouter from "./tradingview_overlay";
import liveIntelligenceMonitorRouter from "./live_intelligence_monitor";
import circuitBreakerRouter from "./circuit_breaker";
import positionSizingRouter from "./position_sizing";
import tradeJournalRouter from "./trade_journal";
import systemOrchestratorRouter from "./system_orchestrator";
import apiGatewayRouter from "./api_gateway";
import dailyReviewRouter from "./daily_review";
import sideBySideRouter from "./side_by_side";
import marketStructureRouter from "./market_structure";
import persistenceRouter from "./persistence";
import siSupervisorRouter from "./si_supervisor";
import observabilityRouter from "./observability";
import governanceRouter from "./governance";
import paperTradingRouter from "./paper_trading";
import liveLaunchRouter from "./live_launch";
import autonomousRouter from "./autonomous";
import executionTruthRouter from "./execution_truth";
import alignmentRouter from "./alignment";
import mlOperationsRouter from "./ml_operations";
import productionHealthRouter from "./production_health";
import certificationRouter from "./certification";
import deploymentTruthRouter from "./deployment_truth";
import dataTruthRouter from "./data_truth";
import executionValidationRouter from "./execution_validation";
import certificationRunRouter from "./certification_run";
import opsV2Router from "./ops_v2";
import governanceSchedulerRouter from "./governance_scheduler";
import calibrationSchedulerRouter from "./calibration_scheduler";
import sloRouter from "./slo";

const router: IRouter = Router();

router.use(governanceRouter);
router.use(healthRouter);
router.use(signalsRouter);
router.use(tradesRouter);
router.use(performanceRouter);
router.use(systemRouter);
router.use(alpacaRouter);
router.use(orderbookRouter);
router.use(strictSetupRouter);
router.use(researchRouter);
router.use(brainRouter);
router.use(superIntelligenceRouter);
router.use(backtestRouter);
router.use(paperValidationRouter);
router.use(alertsRouter);
router.use("/api/checklist", checklistRouter);
router.use("/api/war-room", warRoomRouter);
router.use("/api/proof", proofRouter);
router.use("/api/macro", macroRouter);
router.use("/api/journal", journalRouter);
router.use("/api", watchlistRouter);
router.use("/api", analyticsRouter);
router.use("/api/portfolio", portfolioRouter);
router.use("/api/ops", opsRouter);
router.use("/api/features", featuresRouter);
router.use(engineHealthRouter);
router.use("/api/execution", executionRouter);
router.use("/api", sessionsRouter);
router.use("/api", leaderboardRouter);
router.use(streamingRouter);
router.use(deploymentReadinessRouter);
router.use(autonomyDebuggerRouter);
router.use(autonomyDebugSchedulerRouter);
router.use(autonomySupervisorRouter);
router.use(strategyGovernorRouter);
router.use(strategyAllocatorRouter);
router.use(strategyEvolutionRouter);
router.use(productionWatchdogRouter);
router.use(executionSafetySupervisorRouter);
router.use(brainNodesRouter);
router.use(portfolioAllocatorRouter);
router.use(decisionReplayRouter);
router.use(microstructureRouter);
router.use(contextFusionRouter);
router.use(adaptiveLearningRouter);
router.use(executionIntelligenceRouter);
router.use(strategyRegistryRouter);
router.use(godsviewLabRouter);
router.use(walkForwardStressRouter);
router.use(tradingviewOverlayRouter);
router.use(liveIntelligenceMonitorRouter);
router.use(circuitBreakerRouter);
router.use(positionSizingRouter);
router.use(tradeJournalRouter);
router.use(systemOrchestratorRouter);
router.use(apiGatewayRouter);
router.use("/api", dailyReviewRouter);
router.use("/api", sideBySideRouter);
router.use(persistenceRouter);
router.use("/api", marketStructureRouter);
router.use(siSupervisorRouter);
router.use(observabilityRouter);
router.use(paperTradingRouter);
router.use(liveLaunchRouter);
router.use(autonomousRouter);
router.use("/api/execution-truth", executionTruthRouter);
router.use("/api/alignment", alignmentRouter);
router.use("/api/ml-ops", mlOperationsRouter);
router.use("/api/production-health", productionHealthRouter);
router.use("/api/certification", certificationRouter);

router.use("/api/deployment", deploymentTruthRouter);
router.use("/api/data-truth", dataTruthRouter);
router.use("/api/execution-validation", executionValidationRouter);
router.use("/api/certification-run", certificationRunRouter); // Phase 20 — One strategy certification run
router.use("/api/ops/v2", opsV2Router); // Operator brief, kill switch, exposure, drift, startup

// Phase 5: governance & calibration cron schedulers
router.use(governanceSchedulerRouter);
router.use(calibrationSchedulerRouter);

// Phase 6: SLO definitions, budgets, and burn-rate routes
router.use(sloRouter);

// Python v2 microservices proxy — shadow routes at /v2/*
router.use(pythonV2Router);

// ── Phase 129: Finnhub Alt-Data + S3 Cloud Storage ───────────────────────
import finnhubAltRouter from "./finnhub_alt";
router.use("/api/finnhub", finnhubAltRouter);

import s3StorageRouter from "./s3_storage";
router.use("/api/storage", s3StorageRouter);

export default router;
