import { Router, type IRouter } from "express";
import healthRouter from "./health";
import signalsRouter from "./signals";
import tradesRouter from "./trades";
import performanceRouter from "./performance";
import systemRouter from "./system";
import alpacaRouter from "./alpaca";
import orderbookRouter from "./orderbook";
import strictSetupRouter from "./strict_setup";
import researchRouter from "./research";
import brainRouter from "./brain";
import superIntelligenceRouter from "./super_intelligence";
import backtestRouter from "./backtest";
import paperValidationRouter from "./paper_validation";
import alertsRouter from "./alerts";
import checklistRouter from "./checklist";
import warRoomRouter from "./war_room";
import proofRouter from "./proof";
import macroRouter from "./macro";
import journalRouter from "./journal";
import watchlistRouter from "./watchlist";
import analyticsRouter from "./analytics";
import portfolioRouter from "./portfolio";
import opsRouter from "./ops";
import featuresRouter from "./features";
import engineHealthRouter from "./engine_health";
import executionRouter from "./execution";
import sessionsRouter from "./sessions";
import streamingRouter from "./streaming";
import deploymentReadinessRouter from "./deployment_readiness";
import autonomySupervisorRouter from "./autonomy_supervisor";
import strategyGovernorRouter from "./strategy_governor";
import strategyAllocatorRouter from "./strategy_allocator";
import productionWatchdogRouter from "./production_watchdog";
import leaderboardRouter from "./leaderboard";
import pythonV2Router from "./python_v2";
import brainNodesRouter from "./brain_nodes";
import portfolioAllocatorRouter from "./portfolio_allocator";
import decisionReplayRouter from "./decision_replay";
import microstructureRouter from "./microstructure";

const router: IRouter = Router();

router.use(healthRouter);
router.use(signalsRouter);
router.use(tradesRouter);
router.use(performanceRouter);
router.use(systemRouter);
router.use(alpacaRouter);
router.use(orderbookRouter);
router.use(strictSetupRouter);
router.use(researchRouter);
router.use(brainRouter);
router.use(superIntelligenceRouter);
router.use(backtestRouter);
router.use(paperValidationRouter);
router.use(alertsRouter);
router.use("/api/checklist", checklistRouter);
router.use("/api/war-room", warRoomRouter);
router.use("/api/proof", proofRouter);
router.use("/api/macro", macroRouter);
router.use("/api/journal", journalRouter);
router.use("/api", watchlistRouter);
router.use("/api", analyticsRouter);
router.use("/api/portfolio", portfolioRouter);
router.use("/api/ops", opsRouter);
router.use("/api/features", featuresRouter);
router.use(engineHealthRouter);
router.use("/api/execution", executionRouter);
router.use("/api", sessionsRouter);
router.use("/api", leaderboardRouter);
router.use(streamingRouter);
router.use(deploymentReadinessRouter);
router.use(autonomySupervisorRouter);
router.use(strategyGovernorRouter);
router.use(strategyAllocatorRouter);
router.use(productionWatchdogRouter);
router.use(brainNodesRouter);
router.use(portfolioAllocatorRouter);
router.use(decisionReplayRouter);
router.use(microstructureRouter);

// Python v2 microservices proxy — shadow routes at /v2/*
router.use(pythonV2Router);

export default router;
