/**
 * MCP Backtest API Routes
 *
 * Endpoints for running MCP backtests on historical data with synthetic signal generation:
 *   - POST /mcp-backtest/run - Run a complete MCP backtest
 *   - GET /mcp-backtest/compare/:runId - Get detailed comparison for a backtest run
 *   - GET /mcp-backtest/signal-log/:runId - Get paginated signal decision log
 *   - GET /mcp-backtest/history - List all past backtest runs with summaries
 *
 * Synthetic signals are generated by detecting simple patterns in historical bars
 * (breakouts, pullbacks, etc.), making backtests useful without TradingView history.
 */

import { Router, type Request, type Response } from "express";
import { MCPBacktester, type MCPBacktestConfig, type MCPBacktestResult } from "../lib/tradingview_mcp/backtest_bridge.js";
import { MCPPipelineConfigSchema, type MCPPipelineConfig } from "../lib/tradingview_mcp/types.js";
import type { ReplayBar } from "../lib/backtesting/replay_engine.js";

const router = Router();

// In-memory storage for completed backtest runs
const backtestRuns = new Map<
  string,
  {
    runId: string;
    symbol: string;
    timeframe: string;
    startDate: Date;
    endDate: Date;
    signalType: string;
    initialCapital: number;
    result: MCPBacktestResult;
    createdAt: Date;
  }
>();

// Generate unique run ID
function generateRunId(): string {
  return `backtest_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}

/**
 * Generate synthetic bars for backtesting
 * Creates realistic OHLCV data with trends and volatility
 */
function generateSyntheticBars(
  symbol: string,
  startDate: Date,
  endDate: Date,
  timeframeStr: string,
  initialPrice: number = 100
): ReplayBar[] {
  const bars: ReplayBar[] = [];
  let currentTime = new Date(startDate);
  let price = initialPrice;
  let trend = Math.random() > 0.5 ? 1 : -1;
  let trendStrength = 0.001 + Math.random() * 0.003;

  // Convert timeframe string to milliseconds
  const timeframeMs: Record<string, number> = {
    "1m": 60 * 1000,
    "5m": 5 * 60 * 1000,
    "15m": 15 * 60 * 1000,
    "1h": 60 * 60 * 1000,
    "4h": 4 * 60 * 60 * 1000,
    "1d": 24 * 60 * 60 * 1000,
  };

  const frameDuration = timeframeMs[timeframeStr] || timeframeMs["1d"];

  while (currentTime < endDate) {
    // Update trend randomly
    if (Math.random() < 0.05) {
      trend = Math.random() > 0.5 ? 1 : -1;
      trendStrength = 0.001 + Math.random() * 0.003;
    }

    // Generate OHLC
    const open = price;
    const randomMove = (Math.random() - 0.5) * price * 0.02; // up to 2% move
    const trendMove = trend * price * trendStrength;
    const close = price + randomMove + trendMove;

    const volatility = Math.abs(randomMove) * (0.5 + Math.random());
    const high = Math.max(open, close) + volatility;
    const low = Math.min(open, close) - volatility;

    // Generate volume (roughly 1M shares, with some variance)
    const volume = 500000 + Math.random() * 1500000;

    // Calculate VWAP (simplified)
    const vwap = (open + high + low + close) / 4;

    bars.push({
      symbol,
      timeframe: timeframeStr,
      ts: new Date(currentTime),
      open,
      high,
      low,
      close,
      volume,
      vwap,
    });

    // Update price for next bar
    price = close;
    currentTime = new Date(currentTime.getTime() + frameDuration);
  }

  return bars;
}

/**
 * Detect simple patterns in bars to generate synthetic signals
 * Includes: breakouts, pullbacks, reversals, squeeze patterns
 */
function generateSyntheticSignals(
  bars: ReplayBar[],
  signalType: string
): {
  barIndex: number;
  symbol: string;
  direction: "long" | "short";
  signalType: string;
  timeframe: string;
  stopLoss?: number;
  takeProfit?: number;
  strategyName?: string;
}[] {
  const signals: Array<{
    barIndex: number;
    symbol: string;
    direction: "long" | "short";
    signalType: string;
    timeframe: string;
    stopLoss?: number;
    takeProfit?: number;
    strategyName?: string;
  }> = [];

  const symbol = bars[0].symbol;
  const timeframe = bars[0].timeframe;

  for (let i = 20; i < bars.length; i++) {
    const bar = bars[i];
    const prevBar = bars[i - 1];

    // Simple pattern detection based on requested signal type
    switch (signalType) {
      case "breakout": {
        // Detect breakout above N-bar high
        const nBars = 20;
        const recentBars = bars.slice(Math.max(0, i - nBars), i);
        const high = Math.max(...recentBars.map((b) => b.high));
        if (bar.close > high * 1.001 && bar.close > bar.open) {
          signals.push({
            barIndex: i,
            symbol,
            direction: "long",
            signalType: "breakout",
            timeframe,
            stopLoss: bar.low * 0.97,
            takeProfit: bar.close * 1.06,
            strategyName: "synthetic_breakout",
          });
        }
        break;
      }

      case "breakdown": {
        // Detect breakdown below N-bar low
        const nBars = 20;
        const recentBars = bars.slice(Math.max(0, i - nBars), i);
        const low = Math.min(...recentBars.map((b) => b.low));
        if (bar.close < low * 0.999 && bar.close < bar.open) {
          signals.push({
            barIndex: i,
            symbol,
            direction: "short",
            signalType: "breakdown",
            timeframe,
            stopLoss: bar.high * 1.03,
            takeProfit: bar.close * 0.94,
            strategyName: "synthetic_breakdown",
          });
        }
        break;
      }

      case "pullback_long": {
        // Detect pullback to moving average in uptrend
        const maPeriod = 20;
        if (i >= maPeriod) {
          const recentBars = bars.slice(i - maPeriod, i);
          const ma = recentBars.reduce((sum, b) => sum + b.close, 0) / maPeriod;

          // Uptrend: price above MA
          const above = recentBars.filter((b) => b.close > ma).length > maPeriod * 0.7;
          // Pullback: bar closes near/below MA after uptrend
          if (above && bar.close <= ma * 1.002 && bar.close > ma * 0.99 && bar.close > bar.open) {
            signals.push({
              barIndex: i,
              symbol,
              direction: "long",
              signalType: "pullback_long",
              timeframe,
              stopLoss: bar.low * 0.97,
              takeProfit: bar.close * 1.05,
              strategyName: "synthetic_pullback",
            });
          }
        }
        break;
      }

      case "pullback_short": {
        // Detect pullback to moving average in downtrend
        const maPeriod = 20;
        if (i >= maPeriod) {
          const recentBars = bars.slice(i - maPeriod, i);
          const ma = recentBars.reduce((sum, b) => sum + b.close, 0) / maPeriod;

          // Downtrend: price below MA
          const below = recentBars.filter((b) => b.close < ma).length > maPeriod * 0.7;
          // Pullback: bar closes near/above MA after downtrend
          if (below && bar.close >= ma * 0.998 && bar.close < ma * 1.01 && bar.close < bar.open) {
            signals.push({
              barIndex: i,
              symbol,
              direction: "short",
              signalType: "pullback_short",
              timeframe,
              stopLoss: bar.high * 1.03,
              takeProfit: bar.close * 0.95,
              strategyName: "synthetic_pullback",
            });
          }
        }
        break;
      }

      case "reversal_long": {
        // Detect reversal from downtrend: lower low followed by higher close
        if (i >= 5) {
          const downtrend = bars
            .slice(i - 5, i)
            .slice(0, -1)
            .every((b, idx, arr) => idx === 0 || b.low <= arr[idx - 1].low);
          if (downtrend && bar.close > prevBar.close && bar.close > bar.open) {
            signals.push({
              barIndex: i,
              symbol,
              direction: "long",
              signalType: "reversal_long",
              timeframe,
              stopLoss: bar.low * 0.96,
              takeProfit: bar.close * 1.08,
              strategyName: "synthetic_reversal",
            });
          }
        }
        break;
      }

      case "reversal_short": {
        // Detect reversal from uptrend: higher high followed by lower close
        if (i >= 5) {
          const uptrend = bars
            .slice(i - 5, i)
            .slice(0, -1)
            .every((b, idx, arr) => idx === 0 || b.high >= arr[idx - 1].high);
          if (uptrend && bar.close < prevBar.close && bar.close < bar.open) {
            signals.push({
              barIndex: i,
              symbol,
              direction: "short",
              signalType: "reversal_short",
              timeframe,
              stopLoss: bar.high * 1.04,
              takeProfit: bar.close * 0.92,
              strategyName: "synthetic_reversal",
            });
          }
        }
        break;
      }

      case "squeeze_fire": {
        // Detect squeeze: low volatility followed by breakout
        const sqPeriod = 15;
        if (i >= sqPeriod) {
          const rangeHistory = bars.slice(i - sqPeriod, i).map((b) => b.high - b.low);
          const avgRange = rangeHistory.reduce((a, b) => a + b, 0) / rangeHistory.length;
          const squeezed = rangeHistory[rangeHistory.length - 1] < avgRange * 0.4;
          const breakout = bar.high - bar.low > avgRange * 1.5;

          if (squeezed && breakout) {
            const direction = bar.close > prevBar.close ? "long" : "short";
            signals.push({
              barIndex: i,
              symbol,
              direction,
              signalType: "squeeze_fire",
              timeframe,
              stopLoss: direction === "long" ? bar.low * 0.96 : bar.high * 1.04,
              takeProfit: direction === "long" ? bar.close * 1.08 : bar.close * 0.92,
              strategyName: "synthetic_squeeze",
            });
          }
        }
        break;
      }

      default: {
        // Generic pattern: any significant move
        const priceChange = Math.abs((bar.close - prevBar.close) / prevBar.close);
        if (priceChange > 0.015) {
          // 1.5% move
          const direction = bar.close > prevBar.close ? "long" : "short";
          signals.push({
            barIndex: i,
            symbol,
            direction,
            signalType: "generic_move",
            timeframe,
            stopLoss: direction === "long" ? bar.low * 0.97 : bar.high * 1.03,
            takeProfit: direction === "long" ? bar.close * 1.06 : bar.close * 0.94,
            strategyName: "synthetic_generic",
          });
        }
      }
    }
  }

  return signals;
}

// ── POST /mcp-backtest/run ──────────────────────────────────────────────────────
/**
 * Run an MCP backtest on historical data with synthetic signals
 *
 * Body parameters:
 *   symbol: string (e.g., "SPY")
 *   timeframe: string (e.g., "1h", "1d")
 *   startDate: string (ISO date)
 *   endDate: string (ISO date)
 *   signalType: string (breakout, breakdown, pullback_long, pullback_short, reversal_long, reversal_short, squeeze_fire)
 *   pipelineConfig?: MCPPipelineConfig (optional, uses defaults if not provided)
 *   initialCapital?: number (default: 10000)
 *   runBaseline?: boolean (default: true)
 */
router.post("/mcp-backtest/run", async (req: Request, res: Response): Promise<void> => {
  try {
    const {
      symbol,
      timeframe,
      startDate,
      endDate,
      signalType,
      pipelineConfig,
      initialCapital = 10000,
      runBaseline = true,
    } = req.body;

    // Validate inputs
    if (!symbol || typeof symbol !== "string") {
      res.status(400).json({ error: "Missing or invalid symbol" });
      return;
    }

    if (!timeframe || typeof timeframe !== "string") {
      res.status(400).json({ error: "Missing or invalid timeframe" });
      return;
    }

    if (!startDate || !endDate) {
      res.status(400).json({ error: "Missing startDate or endDate" });
      return;
    }

    if (!signalType || typeof signalType !== "string") {
      res.status(400).json({ error: "Missing or invalid signalType" });
      return;
    }

    const start = new Date(startDate);
    const end = new Date(endDate);

    if (isNaN(start.getTime()) || isNaN(end.getTime())) {
      res.status(400).json({ error: "Invalid date format" });
      return;
    }

    if (start >= end) {
      res.status(400).json({ error: "startDate must be before endDate" });
      return;
    }

    // Use provided pipeline config or create default (zod fills defaults)
    let config: MCPPipelineConfig = MCPPipelineConfigSchema.parse({});

    if (pipelineConfig) {
      config = MCPPipelineConfigSchema.parse({ ...config, ...pipelineConfig });
    }

    // Generate synthetic bars
    const bars = generateSyntheticBars(symbol, start, end, timeframe);

    if (bars.length < 20) {
      res.status(400).json({
        error: "Insufficient data: need at least 20 bars",
        barsGenerated: bars.length,
      });
      return;
    }

    // Generate synthetic signals based on pattern detection
    const signals = generateSyntheticSignals(bars, signalType);

    if (signals.length === 0) {
      res.status(400).json({
        error: "No signals generated for the given pattern and date range",
        suggestion: "Try a different date range or signal type",
      });
      return;
    }

    // Run backtest
    const backtestConfig: MCPBacktestConfig = {
      bars,
      signals,
      initialCapital,
      pipelineConfig: config,
      runBaseline,
    };

    const backtest = new MCPBacktester(backtestConfig);
    const result = await backtest.run();

    // Store result
    const runId = generateRunId();
    backtestRuns.set(runId, {
      runId,
      symbol,
      timeframe,
      startDate: start,
      endDate: end,
      signalType,
      initialCapital,
      result,
      createdAt: new Date(),
    });

    res.json({
      success: true,
      runId,
      summary: {
        symbol,
        timeframe,
        dateRange: {
          start: start.toISOString(),
          end: end.toISOString(),
        },
        signalType,
        initialCapital,
        barsProcessed: bars.length,
        signalsGenerated: signals.length,
        mcpApprovalRate: result.approvalRate,
        mcpMetrics: {
          totalTrades: result.mcpMetrics.totalTrades,
          winRate: result.mcpMetrics.winRate,
          sharpeRatio: result.mcpMetrics.sharpeRatio,
          profitFactor: result.mcpMetrics.profitFactor,
          totalPnl: result.mcpMetrics.totalPnl,
        },
        baselineMetrics: result.baselineMetrics
          ? {
              totalTrades: result.baselineMetrics.totalTrades,
              winRate: result.baselineMetrics.winRate,
              sharpeRatio: result.baselineMetrics.sharpeRatio,
              profitFactor: result.baselineMetrics.profitFactor,
              totalPnl: result.baselineMetrics.totalPnl,
            }
          : null,
        comparison: result.comparison,
      },
    });
  } catch (err) {
    (req as any).log?.error?.({ err }, "MCP backtest failed");
    res.status(500).json({
      error: "backtest_failed",
      message: String(err instanceof Error ? err.message : err),
    });
  }
});

// ── GET /mcp-backtest/compare/:runId ───────────────────────────────────────────
/**
 * Get detailed comparison for a completed backtest run
 * Returns the full MCPComparison object with baseline vs MCP metrics
 */
router.get("/mcp-backtest/compare/:runId", (req: Request, res: Response): void => {
  try {
    const runId = req.params.runId as string;

    const run = backtestRuns.get(runId);
    if (!run) {
      res.status(404).json({ error: "Backtest run not found", runId });
      return;
    }

    const { result } = run;

    if (!result.comparison) {
      res.status(400).json({
        error: "No baseline comparison available",
        message: "This backtest was run without baseline (runBaseline=false)",
      });
      return;
    }

    res.json({
      success: true,
      runId,
      comparison: result.comparison,
      detailed: {
        baseline: {
          totalTrades: result.baselineMetrics?.totalTrades ?? 0,
          winRate: result.baselineMetrics?.winRate ?? 0,
          sharpeRatio: result.baselineMetrics?.sharpeRatio ?? 0,
          profitFactor: result.baselineMetrics?.profitFactor ?? 0,
          totalPnl: result.baselineMetrics?.totalPnl ?? 0,
          avgWin: result.baselineMetrics?.avgWin ?? 0,
          avgLoss: result.baselineMetrics?.avgLoss ?? 0,
          maxDrawdown: result.baselineMetrics?.maxDrawdown ?? 0,
        },
        mcp: {
          totalTrades: result.mcpMetrics.totalTrades,
          winRate: result.mcpMetrics.winRate,
          sharpeRatio: result.mcpMetrics.sharpeRatio,
          profitFactor: result.mcpMetrics.profitFactor,
          totalPnl: result.mcpMetrics.totalPnl,
          avgWin: result.mcpMetrics.avgWin,
          avgLoss: result.mcpMetrics.avgLoss,
          maxDrawdown: result.mcpMetrics.maxDrawdown,
        },
        improvements: {
          winRateImprovement: result.comparison.winRateImprovement,
          sharpeImprovement: result.comparison.sharpeImprovement,
          profitFactorImprovement: result.comparison.profitFactorImprovement,
          pnlImprovement: result.comparison.pnlImprovement,
          tradesFiltered: result.comparison.tradesFiltered,
          tradesFilteredPct: result.comparison.tradesFilteredPct,
          mcpAddedValue: result.comparison.mcpAddedValue,
        },
      },
    });
  } catch (err) {
    (req as any).log?.error?.({ err }, "Compare retrieval failed");
    res.status(500).json({
      error: "compare_failed",
      message: String(err instanceof Error ? err.message : err),
    });
  }
});

// ── GET /mcp-backtest/signal-log/:runId ────────────────────────────────────────
/**
 * Get paginated signal decision log for a backtest run
 *
 * Query parameters:
 *   limit: number (default: 100, max: 1000)
 *   offset: number (default: 0)
 */
router.get("/mcp-backtest/signal-log/:runId", (req: Request, res: Response): void => {
  try {
    const runId = req.params.runId as string;
    const limit = Math.min(parseInt(req.query.limit as string) || 100, 1000);
    const offset = parseInt(req.query.offset as string) || 0;

    const run = backtestRuns.get(runId);
    if (!run) {
      res.status(404).json({ error: "Backtest run not found", runId });
      return;
    }

    const { signalLog } = run.result;

    if (offset >= signalLog.length) {
      res.json({
        success: true,
        runId,
        pagination: {
          offset,
          limit,
          total: signalLog.length,
          hasMore: false,
        },
        signalLog: [],
      });
      return;
    }

    const paginated = signalLog.slice(offset, offset + limit);

    res.json({
      success: true,
      runId,
      pagination: {
        offset,
        limit,
        total: signalLog.length,
        hasMore: offset + limit < signalLog.length,
      },
      signalLog: paginated.map((entry) => ({
        barIndex: entry.barIndex,
        signal: {
          symbol: entry.signal.symbol,
          direction: entry.signal.direction,
          signalType: entry.signal.signalType,
          timeframe: entry.signal.timeframe,
          price: entry.signal.price,
          timestamp: entry.signal.timestamp.toISOString(),
        },
        decision: {
          action: entry.decision.action,
          confidence: entry.decision.confidence,
          reason: (entry.decision as any).reason,
          positionSize: entry.decision.positionSize,
          stopLoss: entry.decision.stopLoss,
          takeProfit: entry.decision.takeProfit,
          regime: entry.decision.enrichment?.regime,
        },
        tradeOutcome: entry.tradeOutcome
          ? {
              pnl: entry.tradeOutcome.pnl,
              pnlPercent: entry.tradeOutcome.pnlPercent,
              holdBars: entry.tradeOutcome.holdBars,
              mae: entry.tradeOutcome.mae,
              mfe: entry.tradeOutcome.mfe,
            }
          : null,
      })),
    });
  } catch (err) {
    (req as any).log?.error?.({ err }, "Signal log retrieval failed");
    res.status(500).json({
      error: "signal_log_failed",
      message: String(err instanceof Error ? err.message : err),
    });
  }
});

// ── GET /mcp-backtest/history ──────────────────────────────────────────────────
/**
 * List all past backtest runs with summaries
 * Returns array of recent runs in reverse chronological order
 */
router.get("/mcp-backtest/history", (req: Request, res: Response): void => {
  try {
    const runs = Array.from(backtestRuns.values())
      .sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
      .map((run) => ({
        runId: run.runId,
        symbol: run.symbol,
        timeframe: run.timeframe,
        signalType: run.signalType,
        initialCapital: run.initialCapital,
        dateRange: {
          start: run.startDate.toISOString(),
          end: run.endDate.toISOString(),
        },
        createdAt: run.createdAt.toISOString(),
        summary: {
          signalsGenerated: run.result.totalSignals,
          signalsApproved: run.result.approvedSignals,
          signalsRejected: run.result.rejectedSignals,
          approvalRate: run.result.approvalRate,
          mcpMetrics: {
            totalTrades: run.result.mcpMetrics.totalTrades,
            winRate: run.result.mcpMetrics.winRate,
            sharpeRatio: run.result.mcpMetrics.sharpeRatio,
            totalPnl: run.result.mcpMetrics.totalPnl,
          },
          comparisonSummary: run.result.comparison?.summary || null,
        },
      }));

    res.json({
      success: true,
      count: runs.length,
      runs,
    });
  } catch (err) {
    (req as any).log?.error?.({ err }, "History retrieval failed");
    res.status(500).json({
      error: "history_failed",
      message: String(err instanceof Error ? err.message : err),
    });
  }
});

export default router;
