import { EventEmitter } from 'events';

/**
 * Configuration for order book imbalance detection
 */
export interface ImbalanceConfig {
  levels?: number;
  imbalanceThreshold?: number;
  updateIntervalMs?: number;
  absorptionWindow?: number;
}

/**
 * Represents a single price level in the order book
 */
export interface BookLevel {
  price: number;
  size: number;
  orderCount: number;
  cumulativeSize: number;
}

/**
 * Complete state of an order book
 */
export interface OrderBookState {
  symbol: string;
  bids: BookLevel[];
  asks: BookLevel[];
  bestBid: number;
  bestAsk: number;
  midPrice: number;
  spread: number;
  spreadBps: number;
  bidDepth: number;
  askDepth: number;
  imbalance: number;
  weightedImbalance: number;
  absorptionRatio: number;
  wallDetected: { side: 'bid' | 'ask'; price: number; size: number } | null;
  timestamp: string;
}

/**
 * Signal generated by imbalance detection
 */
export interface ImbalanceSignal {
  symbol: string;
  type: 'bid_heavy' | 'ask_heavy' | 'balanced' | 'wall_detected' | 'absorption' | 'sweep';
  strength: number;
  direction: 'bullish' | 'bearish' | 'neutral';
  price: number;
  details: string;
  timestamp: string;
}

/**
 * Depth profile and liquidity distribution
 */
export interface DepthProfile {
  symbol: string;
  bidLiquidity: { depth1: number; depth5: number; depth10: number };
  askLiquidity: { depth1: number; depth5: number; depth10: number };
  asymmetry: number;
  resilience: number;
  timestamp: string;
}

/**
 * OrderBookImbalance class extends EventEmitter to detect and analyze
 * order book imbalances, walls, and other microstructure patterns
 */
export class OrderBookImbalance extends EventEmitter {
  private config: Required<ImbalanceConfig>;
  private books: Map<string, OrderBookState> = new Map();
  private imbalanceHistory: Map<string, Array<{ timestamp: string; imbalance: number }>> = new Map();
  private absorptionTracking: Map<string, { timestamp: number; volume: number }[]> = new Map();
  private lastUpdate: Map<string, number> = new Map();

  constructor(config: ImbalanceConfig = {}) {
    super();
    this.config = {
      levels: config.levels ?? 10,
      imbalanceThreshold: config.imbalanceThreshold ?? 0.3,
      updateIntervalMs: config.updateIntervalMs ?? 1000,
      absorptionWindow: config.absorptionWindow ?? 30,
    };
  }

  /**
   * Update order book with new bid/ask data
   */
  public updateBook(
    symbol: string,
    bids: { price: number; size: number }[],
    asks: { price: number; size: number }[]
  ): ImbalanceSignal | null {
    const now = Date.now();
    const lastUpdateTime = this.lastUpdate.get(symbol) ?? 0;

    if (now - lastUpdateTime < this.config.updateIntervalMs) {
      return null;
    }

    this.lastUpdate.set(symbol, now);

    const bidLevels = this.buildLevels(bids.slice(0, this.config.levels));
    const askLevels = this.buildLevels(asks.slice(0, this.config.levels));

    const bestBid = bidLevels.length > 0 ? bidLevels[0].price : 0;
    const bestAsk = askLevels.length > 0 ? askLevels[0].price : 0;
    const midPrice = bestBid && bestAsk ? (bestBid + bestAsk) / 2 : 0;
    const spread = bestAsk - bestBid;
    const spreadBps = midPrice > 0 ? (spread / midPrice) * 10000 : 0;

    const bidDepth = bidLevels.reduce((sum, level) => sum + level.size, 0);
    const askDepth = askLevels.reduce((sum, level) => sum + level.size, 0);

    const imbalance = this.calculateImbalance(bidDepth, askDepth);
    const weightedImbalance = this.calculateWeightedImbalance(bidLevels, askLevels, midPrice);
    const absorptionRatio = this.calculateAbsorptionRatio(symbol, bidDepth, askDepth);

    const walls = this.detectWalls(symbol, 3);
    let wallDetected: { side: 'bid' | 'ask'; price: number; size: number } | null = null;
    if (walls.length > 0) {
      const wall = walls[0];
      wallDetected = {
        side: wall.side as 'bid' | 'ask',
        price: wall.price,
        size: wall.size,
      };
    }

    const state: OrderBookState = {
      symbol,
      bids: bidLevels,
      asks: askLevels,
      bestBid,
      bestAsk,
      midPrice,
      spread,
      spreadBps,
      bidDepth,
      askDepth,
      imbalance,
      weightedImbalance,
      absorptionRatio,
      wallDetected,
      timestamp: new Date().toISOString(),
    };

    this.books.set(symbol, state);
    this.recordImbalanceHistory(symbol, imbalance);

    return this.generateSignal(symbol, state);
  }

  /**
   * Get the current state of an order book
   */
  public getBookState(symbol: string): OrderBookState | undefined {
    return this.books.get(symbol);
  }

  /**
   * Get imbalance history for a symbol
   */
  public getImbalanceHistory(symbol: string, periodMs: number = 60000): Array<{ timestamp: string; imbalance: number }> {
    const history = this.imbalanceHistory.get(symbol) ?? [];
    if (periodMs === 0) return history;

    const cutoff = Date.now() - periodMs;
    return history.filter((entry) => new Date(entry.timestamp).getTime() > cutoff);
  }

  /**
   * Get depth profile and liquidity distribution
   */
  public getDepthProfile(symbol: string): DepthProfile {
    const state = this.books.get(symbol);
    if (!state) {
      return {
        symbol,
        bidLiquidity: { depth1: 0, depth5: 0, depth10: 0 },
        askLiquidity: { depth1: 0, depth5: 0, depth10: 0 },
        asymmetry: 0,
        resilience: 0,
        timestamp: new Date().toISOString(),
      };
    }

    const bidLiquidity = {
      depth1: state.bids.slice(0, 1).reduce((sum, l) => sum + l.size, 0),
      depth5: state.bids.slice(0, 5).reduce((sum, l) => sum + l.size, 0),
      depth10: state.bids.slice(0, 10).reduce((sum, l) => sum + l.size, 0),
    };

    const askLiquidity = {
      depth1: state.asks.slice(0, 1).reduce((sum, l) => sum + l.size, 0),
      depth5: state.asks.slice(0, 5).reduce((sum, l) => sum + l.size, 0),
      depth10: state.asks.slice(0, 10).reduce((sum, l) => sum + l.size, 0),
    };

    const asymmetry = Math.abs(bidLiquidity.depth5 - askLiquidity.depth5) / (bidLiquidity.depth5 + askLiquidity.depth5 || 1);
    const resilience = (state.bidDepth + state.askDepth) / (state.spread + 1);

    return {
      symbol,
      bidLiquidity,
      askLiquidity,
      asymmetry,
      resilience,
      timestamp: state.timestamp,
    };
  }

  /**
   * Detect walls (large orders at a single price)
   */
  public detectWalls(
    symbol: string,
    minMultiplier: number = 3
  ): Array<{ side: string; price: number; size: number; avgSize: number; multiplier: number }> {
    const state = this.books.get(symbol);
    if (!state) return [];

    const walls: Array<{ side: string; price: number; size: number; avgSize: number; multiplier: number }> = [];

    const checkLevels = (levels: BookLevel[], side: string) => {
      if (levels.length < 2) return;

      const avgSize = levels.reduce((sum, l) => sum + l.size, 0) / levels.length;
      levels.forEach((level) => {
        const multiplier = level.size / (avgSize || 1);
        if (multiplier >= minMultiplier) {
          walls.push({
            side,
            price: level.price,
            size: level.size,
            avgSize,
            multiplier,
          });
        }
      });
    };

    checkLevels(state.bids, 'bid');
    checkLevels(state.asks, 'ask');

    return walls.sort((a, b) => b.multiplier - a.multiplier);
  }

  /**
   * Detect sweep (large volume clearing multiple levels)
   */
  public detectSweep(symbol: string): { side: string; levelsCleared: number; volumeSwept: number; priceMove: number } | null {
    const state = this.books.get(symbol);
    if (!state || state.bids.length === 0 || state.asks.length === 0) {
      return null;
    }

    const checkSide = (levels: BookLevel[]): { levelsCleared: number; volumeSwept: number } | null => {
      let levelsCleared = 0;
      let volumeSwept = 0;

      for (const level of levels) {
        if (level.size === 0) {
          levelsCleared++;
          volumeSwept += level.cumulativeSize;
        } else {
          break;
        }
      }

      return levelsCleared > 0 ? { levelsCleared, volumeSwept } : null;
    };

    const bidSweep = checkSide(state.bids);
    const askSweep = checkSide(state.asks);

    if (bidSweep && bidSweep.volumeSwept > state.askDepth * 0.5) {
      const priceMove = state.bestBid - (bidSweep.levelsCleared > 0 ? state.bids[bidSweep.levelsCleared - 1]?.price : state.bestBid);
      return {
        side: 'bid',
        levelsCleared: bidSweep.levelsCleared,
        volumeSwept: bidSweep.volumeSwept,
        priceMove,
      };
    }

    if (askSweep && askSweep.volumeSwept > state.bidDepth * 0.5) {
      const priceMove = (askSweep.levelsCleared > 0 ? state.asks[askSweep.levelsCleared - 1]?.price : state.bestAsk) - state.bestAsk;
      return {
        side: 'ask',
        levelsCleared: askSweep.levelsCleared,
        volumeSwept: askSweep.volumeSwept,
        priceMove,
      };
    }

    return null;
  }

  /**
   * Get all tracked symbols
   */
  public getSymbols(): string[] {
    return Array.from(this.books.keys());
  }

  /**
   * Reset data for a symbol or all symbols
   */
  public reset(symbol?: string): void {
    if (symbol) {
      this.books.delete(symbol);
      this.imbalanceHistory.delete(symbol);
      this.absorptionTracking.delete(symbol);
      this.lastUpdate.delete(symbol);
    } else {
      this.books.clear();
      this.imbalanceHistory.clear();
      this.absorptionTracking.clear();
      this.lastUpdate.clear();
    }
  }

  /**
   * Build BookLevel array from price/size pairs
   */
  private buildLevels(data: { price: number; size: number }[]): BookLevel[] {
    let cumulativeSize = 0;
    return data.map((item) => {
      cumulativeSize += item.size;
      return {
        price: item.price,
        size: item.size,
        orderCount: 1,
        cumulativeSize,
      };
    });
  }

  /**
   * Calculate simple imbalance ratio
   */
  private calculateImbalance(bidDepth: number, askDepth: number): number {
    const total = bidDepth + askDepth;
    if (total === 0) return 0;
    return (bidDepth - askDepth) / total;
  }

  /**
   * Calculate weighted imbalance (closer to mid weighs more)
   */
  private calculateWeightedImbalance(bidLevels: BookLevel[], askLevels: BookLevel[], midPrice: number): number {
    if (bidLevels.length === 0 || askLevels.length === 0) return 0;

    let bidWeightedVolume = 0;
    let askWeightedVolume = 0;
    let totalWeight = 0;

    bidLevels.forEach((level, index) => {
      const weight = 1 / (index + 1);
      bidWeightedVolume += level.size * weight;
      totalWeight += weight;
    });

    askLevels.forEach((level, index) => {
      const weight = 1 / (index + 1);
      askWeightedVolume += level.size * weight;
      totalWeight += weight;
    });

    return (bidWeightedVolume - askWeightedVolume) / (bidWeightedVolume + askWeightedVolume || 1);
  }

  /**
   * Calculate absorption ratio for best bid/ask
   */
  private calculateAbsorptionRatio(symbol: string, bidDepth: number, askDepth: number): number {
    if (!this.absorptionTracking.has(symbol)) {
      this.absorptionTracking.set(symbol, []);
    }

    const tracking = this.absorptionTracking.get(symbol)!;
    const now = Date.now();
    const windowMs = this.config.absorptionWindow * 1000;

    tracking.push({ timestamp: now, volume: bidDepth + askDepth });
    const filtered = tracking.filter((entry) => now - entry.timestamp < windowMs);
    this.absorptionTracking.set(symbol, filtered);

    if (filtered.length < 2) return 0;

    const volumeAdded = filtered[filtered.length - 1].volume - filtered[0].volume;
    const volumeAbsorbed = bidDepth + askDepth;

    return volumeAdded > 0 ? volumeAbsorbed / volumeAdded : 0;
  }

  /**
   * Record imbalance value in history
   */
  private recordImbalanceHistory(symbol: string, imbalance: number): void {
    if (!this.imbalanceHistory.has(symbol)) {
      this.imbalanceHistory.set(symbol, []);
    }

    const history = this.imbalanceHistory.get(symbol)!;
    history.push({
      timestamp: new Date().toISOString(),
      imbalance,
    });

    if (history.length > 1000) {
      history.shift();
    }
  }

  /**
   * Generate signal based on order book state
   */
  private generateSignal(symbol: string, state: OrderBookState): ImbalanceSignal | null {
    const absImbalance = Math.abs(state.imbalance);
    const absWeightedImbalance = Math.abs(state.weightedImbalance);

    let signal: ImbalanceSignal | null = null;

    if (state.wallDetected) {
      signal = {
        symbol,
        type: 'wall_detected',
        strength: absWeightedImbalance,
        direction: state.imbalance > 0 ? 'bullish' : 'bearish',
        price: state.wallDetected.price,
        details: `Wall detected on ${state.wallDetected.side} side: ${state.wallDetected.size} units at ${state.wallDetected.price}`,
        timestamp: state.timestamp,
      };
      this.emit('wall:detected', signal);
      return signal;
    }

    const sweep = this.detectSweep(symbol);
    if (sweep && sweep.volumeSwept > 0) {
      signal = {
        symbol,
        type: 'sweep',
        strength: Math.min(sweep.volumeSwept / (state.bidDepth + state.askDepth), 1),
        direction: sweep.side === 'bid' ? 'bearish' : 'bullish',
        price: sweep.side === 'bid' ? state.bestBid : state.bestAsk,
        details: `Sweep detected on ${sweep.side} side: ${sweep.levelsCleared} levels cleared, ${sweep.volumeSwept} volume`,
        timestamp: state.timestamp,
      };
      this.emit('sweep:detected', signal);
      return signal;
    }

    if (state.absorptionRatio > 1.5) {
      signal = {
        symbol,
        type: 'absorption',
        strength: Math.min(state.absorptionRatio / 3, 1),
        direction: state.imbalance > 0 ? 'bullish' : 'bearish',
        price: state.midPrice,
        details: `High absorption ratio: ${state.absorptionRatio.toFixed(2)}x over ${this.config.absorptionWindow}s window`,
        timestamp: state.timestamp,
      };
      this.emit('absorption:signal', signal);
      return signal;
    }

    if (absImbalance > this.config.imbalanceThreshold) {
      const isBidHeavy = state.imbalance > 0;
      signal = {
        symbol,
        type: isBidHeavy ? 'bid_heavy' : 'ask_heavy',
        strength: Math.min(absImbalance, 1),
        direction: isBidHeavy ? 'bullish' : 'bearish',
        price: state.midPrice,
        details: `${isBidHeavy ? 'Bid' : 'Ask'} heavy imbalance: ${(state.imbalance * 100).toFixed(2)}%`,
        timestamp: state.timestamp,
      };
      this.emit('imbalance:detected', signal);
      return signal;
    }

    return null;
  }
}
