#!/usr/bin/env python3
"""
GodsView Crypto Signal Engine - Live Paper Trading
==================================================
Real-time crypto signal generation using market structure analysis.
Runs validated backtest strategies in PAPER TRADING ONLY mode.

Strategies:
- SOLUSD 4h (PF=7.33, WR=81.2%)
- ETHUSD 1h (PF=10.58, WR=76.9%)
- BTCUSD 4h (PF=2.02, WR=47.1%)

Exchange: Kraken via ccxt
Mode: PAPER ONLY - no real money trades
"""

import json
import logging
import threading
import time
from datetime import datetime, timedelta
from collections import deque, defaultdict
from typing import Dict, List, Tuple, Optional, Any
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import ccxt
from flask import Flask, jsonify, request
from dataclasses import dataclass, asdict

# ============================================================================
# CONFIGURATION
# ============================================================================

STRATEGIES_CONFIG = {
    'SOLUSD_4h': {
        'symbol': 'SOL/USD',
        'timeframe': '4h',
        'profit_factor': 7.33,
        'win_rate': 81.2,
        'lookback_candles': 100,
        'enabled': True,
    },
    'ETHUSD_1h': {
        'symbol': 'ETH/USD',
        'timeframe': '1h',
        'profit_factor': 10.58,
        'win_rate': 76.9,
        'lookback_candles': 100,
        'enabled': True,
    },
    'BTCUSD_4h': {
        'symbol': 'BTC/USD',
        'timeframe': '4h',
        'profit_factor': 2.02,
        'win_rate': 47.1,
        'lookback_candles': 100,
        'enabled': True,
    },
}

TRADING_CONFIG = {
    'mode': 'PAPER',
    'starting_capital': 100000.0,
    'risk_per_trade': 0.01,  # 1% of capital
    'exchange': 'kraken',
    'max_concurrent_positions': 3,
    'max_positions_per_symbol': 1,
    'max_daily_loss_pct': 3.0,  # 3% of capital
    'max_drawdown_pct': 10.0,  # 10% of capital
    'max_weekly_drawdown_pct': 5.0,  # 5% of capital
    'consecutive_loss_threshold': 3,  # Circuit breaker
    'strategy_pause_duration': 86400,  # 24 hours in seconds
}

# Auto-detect base directory (works on EC2 and local)
import os as _os
_SCRIPT_DIR = Path(_os.path.dirname(_os.path.abspath(__file__)))
_BASE_DIR = _SCRIPT_DIR.parent  # /home/ubuntu/Godsview or local workspace root
_DATA_DIR = _BASE_DIR / 'docs' / 'backtests' / 'paper_trading'

ALERT_DIRS = {
    'alerts': _DATA_DIR / 'alerts',
    'positions': _DATA_DIR / 'positions',
    'performance': _DATA_DIR / 'performance',
}

# Create alert directories if they don't exist
for dir_path in ALERT_DIRS.values():
    dir_path.mkdir(parents=True, exist_ok=True)

# ============================================================================
# LOGGING SETUP
# ============================================================================

def setup_logging():
    """Configure logging with both file and console output."""
    log_dir = _BASE_DIR / 'logs'
    log_dir.mkdir(parents=True, exist_ok=True)
    
    log_file = log_dir / f'signal_engine_{datetime.now().strftime("%Y%m%d_%H%M%S")}.log'
    
    logging.basicConfig(
        level=logging.DEBUG,
        format='%(asctime)s - %(name)s - %(levelname)s - [PAPER MODE] %(message)s',
        handlers=[
            logging.FileHandler(log_file),
            logging.StreamHandler(sys.stdout)
        ]
    )
    return logging.getLogger(__name__)

logger = setup_logging()

# ============================================================================
# DATA CLASSES
# ============================================================================

@dataclass
class Swing:
    """Swing point in market structure."""
    timestamp: int
    price: float
    type: str  # 'high' or 'low'
    
@dataclass
class OrderBlock:
    """Order block (accumulation/distribution zone)."""
    start_idx: int
    end_idx: int
    high: float
    low: float
    type: str  # 'bullish' or 'bearish'
    strength: float  # 0-100
    
@dataclass
class Signal:
    """Trading signal generated by the engine."""
    timestamp: datetime
    symbol: str
    timeframe: str
    strategy_name: str
    direction: str  # 'LONG' or 'SHORT'
    entry_price: float
    stop_loss: float
    take_profit: float
    confidence_score: float  # 0-100
    risk_amount: float
    position_size: float
    invalidation_level: float
    order_blocks_used: List[OrderBlock]
    flow_confirmation: Dict[str, Any]
    
@dataclass
class PaperPosition:
    """Simulated paper trading position."""
    position_id: str
    symbol: str
    timeframe: str
    strategy_name: str
    direction: str
    entry_price: float
    entry_time: datetime
    stop_loss: float
    take_profit: float
    position_size: float
    risk_amount: float
    pnl: float
    pnl_pct: float
    status: str  # 'open', 'closed_sl', 'closed_tp', 'closed_time'
    close_time: Optional[datetime]
    close_price: Optional[float]
    close_reason: str
    candles_held: int

# ============================================================================
# MARKET STRUCTURE DETECTION
# ============================================================================

class MarketStructureAnalyzer:
    """Detects market structure: swings, order blocks, and flow."""
    
    def __init__(self):
        pass
    
    def detect_swing_points(
        self, 
        df: pd.DataFrame, 
        lookback: int = 10
    ) -> List[Swing]:
        """
        Detect swing high and swing low points.
        
        A swing high is a candle higher than 'lookback' candles before and after.
        A swing low is a candle lower than 'lookback' candles before and after.
        """
        swings = []
        df = df.copy()
        
        if len(df) < lookback * 2:
            return swings
        
        highs = df['high'].values
        lows = df['low'].values
        close = df['close'].values
        
        for i in range(lookback, len(df) - lookback):
            # Swing high
            if highs[i] == max(highs[i-lookback:i+lookback+1]):
                swings.append(Swing(
                    timestamp=int(df.index[i].timestamp()),
                    price=float(highs[i]),
                    type='high'
                ))
            
            # Swing low
            if lows[i] == min(lows[i-lookback:i+lookback+1]):
                swings.append(Swing(
                    timestamp=int(df.index[i].timestamp()),
                    price=float(lows[i]),
                    type='low'
                ))
        
        return sorted(swings, key=lambda x: x.timestamp)
    
    def detect_bos_choch(self, swings: List[Swing]) -> Dict[str, Any]:
        """
        Detect Break of Structure (BOS) and Change of Character (CHOCH).
        
        BOS: Price breaks above/below previous swing without changing direction
        CHOCH: Price breaks and changes from uptrend to downtrend (or vice versa)
        """
        if len(swings) < 3:
            return {'bos': None, 'choch': None}
        
        result = {'bos': None, 'choch': None}
        
        # Get last 3 significant swings
        recent_swings = swings[-3:]
        
        if len(recent_swings) == 3:
            s1, s2, s3 = recent_swings
            
            # Determine trend
            if s1.type == 'low' and s2.type == 'high' and s3.type == 'low':
                # Downtrend: low -> high -> lower low = BOS
                if s3.price < s1.price:
                    result['bos'] = {'direction': 'down', 'level': s1.price}
                    result['choch'] = {'direction': 'down', 'level': s3.price}
            
            elif s1.type == 'high' and s2.type == 'low' and s3.type == 'high':
                # Uptrend: high -> low -> higher high = BOS
                if s3.price > s1.price:
                    result['bos'] = {'direction': 'up', 'level': s1.price}
                    result['choch'] = {'direction': 'up', 'level': s3.price}
        
        return result
    
    def detect_order_blocks(self, df: pd.DataFrame) -> List[OrderBlock]:
        """
        Detect order blocks (accumulation/distribution zones).
        
        Bullish OB: Sharp down movement followed by consolidation
        Bearish OB: Sharp up movement followed by consolidation
        
        Strength scored 0-100 based on:
        - Size of initial impulse
        - Consolidation time
        - Proximity to current price
        """
        order_blocks = []
        df = df.copy()
        
        if len(df) < 20:
            return order_blocks
        
        closes = df['close'].values
        highs = df['high'].values
        lows = df['low'].values
        
        for i in range(10, len(df) - 5):
            # Bullish OB: Look for down impulse followed by consolidation
            if i >= 20:
                # Check if we had a sharp down move
                down_move = closes[i-10:i-5]
                current_zone = closes[i-5:i]
                
                if np.mean(down_move) > np.mean(current_zone):
                    down_pct = (np.mean(down_move) - np.mean(current_zone)) / np.mean(down_move)
                    if down_pct > 0.01:  # At least 1% move
                        strength = min(100, down_pct * 1000 + 50)
                        order_blocks.append(OrderBlock(
                            start_idx=i-10,
                            end_idx=i,
                            high=float(np.max(current_zone)),
                            low=float(np.min(current_zone)),
                            type='bullish',
                            strength=float(strength)
                        ))
            
            # Bearish OB: Look for up impulse followed by consolidation
            if i >= 20:
                up_move = closes[i-10:i-5]
                current_zone = closes[i-5:i]
                
                if np.mean(up_move) < np.mean(current_zone):
                    up_pct = (np.mean(current_zone) - np.mean(up_move)) / np.mean(up_move)
                    if up_pct > 0.01:  # At least 1% move
                        strength = min(100, up_pct * 1000 + 50)
                        order_blocks.append(OrderBlock(
                            start_idx=i-10,
                            end_idx=i,
                            high=float(np.max(current_zone)),
                            low=float(np.min(current_zone)),
                            type='bearish',
                            strength=float(strength)
                        ))
        
        return order_blocks
    
    def detect_liquidity_sweeps(
        self, 
        df: pd.DataFrame, 
        swings: List[Swing]
    ) -> Dict[str, Any]:
        """
        Detect liquidity sweeps (stops are hit, then reversals).
        """
        if len(swings) < 2:
            return {'sweeps': []}
        
        sweeps = []
        lows = df['low'].values
        highs = df['high'].values
        
        for i in range(1, len(swings)):
            prev_swing = swings[i-1]
            curr_swing = swings[i]
            
            if prev_swing.type == 'low' and curr_swing.type == 'high':
                # Check if price went below prev low
                min_price_since = np.min(lows[max(0, i-5):i+1])
                if min_price_since < prev_swing.price:
                    sweeps.append({
                        'level': prev_swing.price,
                        'type': 'liquidity_below',
                        'touched_at': datetime.now()
                    })
            
            elif prev_swing.type == 'high' and curr_swing.type == 'low':
                # Check if price went above prev high
                max_price_since = np.max(highs[max(0, i-5):i+1])
                if max_price_since > prev_swing.price:
                    sweeps.append({
                        'level': prev_swing.price,
                        'type': 'liquidity_above',
                        'touched_at': datetime.now()
                    })
        
        return {'sweeps': sweeps}

# ============================================================================
# ORDER FLOW ANALYSIS (OHLCV-Based Proxy)
# ============================================================================

class OrderFlowAnalyzer:
    """Analyzes order flow using OHLCV-based proxies."""
    
    @staticmethod
    def calculate_clv(df: pd.DataFrame) -> pd.Series:
        """
        Close Location Value (CLV).
        How close the close is relative to high-low range.
        CLV = ((C - L) - (H - C)) / (H - L)
        """
        numerator = (df['close'] - df['low']) - (df['high'] - df['close'])
        denominator = df['high'] - df['low']
        denominator = denominator.replace(0, 1)  # Avoid division by zero
        return numerator / denominator
    
    @staticmethod
    def calculate_delta_proxy(df: pd.DataFrame) -> pd.Series:
        """
        Delta proxy using volume and close position.
        Positive close at high suggests buying pressure.
        Negative close at low suggests selling pressure.
        """
        clv = OrderFlowAnalyzer.calculate_clv(df)
        return df['volume'] * clv
    
    @staticmethod
    def calculate_cvd(df: pd.DataFrame) -> pd.Series:
        """
        Cumulative Volume Delta (CVD).
        Sum of delta proxies over time.
        """
        delta = OrderFlowAnalyzer.calculate_delta_proxy(df)
        return delta.cumsum()
    
    @staticmethod
    def detect_absorption(df: pd.DataFrame, lookback: int = 20) -> Dict[str, Any]:
        """
        Detect absorption (institutional buying/selling).
        
        Absorption occurs when price doesn't move significantly despite
        large volume (delta proxy).
        """
        if len(df) < lookback:
            return {'absorption': False, 'type': None, 'strength': 0}
        
        recent = df.tail(lookback)
        price_range = (recent['high'].max() - recent['low'].min()) / recent['close'].iloc[0]
        volume_avg = recent['volume'].mean()
        current_volume = recent['volume'].iloc[-1]
        
        # Strong absorption: high volume but low price movement
        if current_volume > volume_avg * 1.5 and price_range < 0.01:  # Less than 1% range
            delta = OrderFlowAnalyzer.calculate_delta_proxy(recent)
            if abs(delta.iloc[-1]) > volume_avg * 0.7:
                absorption_type = 'bullish' if delta.iloc[-1] > 0 else 'bearish'
                return {
                    'absorption': True,
                    'type': absorption_type,
                    'strength': min(100, abs(delta.iloc[-1]) / volume_avg * 100)
                }
        
        return {'absorption': False, 'type': None, 'strength': 0}
    
    @staticmethod
    def detect_imbalance(df: pd.DataFrame, lookback: int = 5) -> Dict[str, Any]:
        """
        Detect volume imbalances (strong directional pressure).
        """
        if len(df) < lookback:
            return {'imbalance': False, 'direction': None}
        
        recent = df.tail(lookback)
        delta = OrderFlowAnalyzer.calculate_delta_proxy(recent)
        cvd = delta.cumsum()
        
        imbalance_strength = abs(cvd.iloc[-1]) / (recent['volume'].sum() + 1)
        
        if imbalance_strength > 0.3:  # >30% imbalance
            direction = 'bullish' if cvd.iloc[-1] > 0 else 'bearish'
            return {
                'imbalance': True,
                'direction': direction,
                'strength': min(100, imbalance_strength * 100)
            }
        
        return {'imbalance': False, 'direction': None}

# ============================================================================
# SIGNAL GENERATION ENGINE
# ============================================================================

class SignalGenerator:
    """Generates trading signals based on market structure and flow."""
    
    def __init__(self):
        self.structure_analyzer = MarketStructureAnalyzer()
        self.flow_analyzer = OrderFlowAnalyzer()
    
    def generate_signals(
        self,
        symbol: str,
        timeframe: str,
        df: pd.DataFrame,
        strategy_name: str
    ) -> List[Signal]:
        """Generate trading signals for a given symbol and timeframe."""
        signals = []
        
        if len(df) < 30:
            return signals
        
        # Detect market structure
        swings = self.structure_analyzer.detect_swing_points(df, lookback=10)
        bos_choch = self.structure_analyzer.detect_bos_choch(swings) or {}
        order_blocks = self.structure_analyzer.detect_order_blocks(df) or []
        liquidity = self.structure_analyzer.detect_liquidity_sweeps(df, swings) or []

        # Analyze order flow
        absorption = self.flow_analyzer.detect_absorption(df) or {}
        imbalance = self.flow_analyzer.detect_imbalance(df) or {}

        # Null-safe: ensure nested dicts are not None
        if bos_choch.get('bos') is None:
            bos_choch['bos'] = {}
        if bos_choch.get('choch') is None:
            bos_choch['choch'] = {}
        
        current_price = df['close'].iloc[-1]
        current_time = pd.Timestamp(df.index[-1])
        
        # Signal 1: OB_Retest_Long
        # Conditions: Price retests bullish OB + BOS + flow confirmation
        for ob in order_blocks:
            if ob.type == 'bullish' and current_price >= ob.low and current_price <= ob.high:
                # Price in order block
                if bos_choch.get('bos', {}).get('direction') == 'up':
                    # BOS to upside confirms strength
                    if imbalance.get('direction') == 'bullish':
                        # Bullish imbalance confirms
                        confidence = (
                            ob.strength * 0.3 +
                            imbalance.get('strength', 0) * 0.4 +
                            (80 if absorption.get('type') == 'bullish' else 40) * 0.3
                        )
                        
                        if confidence > 60:
                            signals.append(self._create_signal(
                                symbol=symbol,
                                timeframe=timeframe,
                                strategy_name=strategy_name,
                                direction='LONG',
                                entry_price=current_price,
                                stop_loss=ob.low * 0.99,  # Below order block
                                take_profit=current_price * 1.03,  # 3% TP
                                confidence_score=confidence,
                                order_blocks_used=[ob],
                                flow_confirmation={
                                    'imbalance': imbalance.get('direction'),
                                    'absorption': absorption.get('type'),
                                    'bos': bos_choch.get('bos')
                                },
                                timestamp=current_time
                            ))
        
        # Signal 2: OB_Retest_Short
        # Conditions: Price retests bearish OB + CHOCH + flow confirmation
        for ob in order_blocks:
            if ob.type == 'bearish' and current_price >= ob.low and current_price <= ob.high:
                # Price in order block
                if bos_choch.get('bos', {}).get('direction') == 'down':
                    # BOS to downside confirms weakness
                    if imbalance.get('direction') == 'bearish':
                        # Bearish imbalance confirms
                        confidence = (
                            ob.strength * 0.3 +
                            imbalance.get('strength', 0) * 0.4 +
                            (80 if absorption.get('type') == 'bearish' else 40) * 0.3
                        )
                        
                        if confidence > 60:
                            signals.append(self._create_signal(
                                symbol=symbol,
                                timeframe=timeframe,
                                strategy_name=strategy_name,
                                direction='SHORT',
                                entry_price=current_price,
                                stop_loss=ob.high * 1.01,  # Above order block
                                take_profit=current_price * 0.97,  # 3% TP
                                confidence_score=confidence,
                                order_blocks_used=[ob],
                                flow_confirmation={
                                    'imbalance': imbalance.get('direction'),
                                    'absorption': absorption.get('type'),
                                    'bos': bos_choch.get('bos')
                                },
                                timestamp=current_time
                            ))
        
        # Signal 3: Breakout_Retest
        # Price breaks support/resistance and comes back to retest
        if len(swings) >= 2:
            last_swing = swings[-1]
            prev_price = df['close'].iloc[-2]
            
            if last_swing.type == 'low' and prev_price > last_swing.price and current_price < last_swing.price:
                # Broke below support (downside breakout)
                if imbalance.get('direction') == 'bearish':
                    confidence = 50 + imbalance.get('strength', 0) * 0.5
                    signals.append(self._create_signal(
                        symbol=symbol,
                        timeframe=timeframe,
                        strategy_name=strategy_name,
                        direction='SHORT',
                        entry_price=current_price,
                        stop_loss=last_swing.price * 1.01,
                        take_profit=current_price * 0.97,
                        confidence_score=confidence,
                        order_blocks_used=[],
                        flow_confirmation={'breakout': 'down', 'imbalance': imbalance},
                        timestamp=current_time
                    ))
            
            elif last_swing.type == 'high' and prev_price < last_swing.price and current_price > last_swing.price:
                # Broke above resistance (upside breakout)
                if imbalance.get('direction') == 'bullish':
                    confidence = 50 + imbalance.get('strength', 0) * 0.5
                    signals.append(self._create_signal(
                        symbol=symbol,
                        timeframe=timeframe,
                        strategy_name=strategy_name,
                        direction='LONG',
                        entry_price=current_price,
                        stop_loss=last_swing.price * 0.99,
                        take_profit=current_price * 1.03,
                        confidence_score=confidence,
                        order_blocks_used=[],
                        flow_confirmation={'breakout': 'up', 'imbalance': imbalance},
                        timestamp=current_time
                    ))
        
        return signals
    
    def _create_signal(
        self,
        symbol: str,
        timeframe: str,
        strategy_name: str,
        direction: str,
        entry_price: float,
        stop_loss: float,
        take_profit: float,
        confidence_score: float,
        order_blocks_used: List[OrderBlock],
        flow_confirmation: Dict[str, Any],
        timestamp: pd.Timestamp
    ) -> Signal:
        """Helper to create a Signal object."""
        risk = abs(entry_price - stop_loss)
        reward = abs(take_profit - entry_price)
        
        # Risk per trade is 1% of capital
        capital = TRADING_CONFIG['starting_capital']
        risk_amount = capital * TRADING_CONFIG['risk_per_trade']
        position_size = risk_amount / risk if risk > 0 else 0
        
        return Signal(
            timestamp=pd.Timestamp(timestamp).to_pydatetime(),
            symbol=symbol,
            timeframe=timeframe,
            strategy_name=strategy_name,
            direction=direction,
            entry_price=entry_price,
            stop_loss=stop_loss,
            take_profit=take_profit,
            confidence_score=min(100, max(0, confidence_score)),
            risk_amount=risk_amount,
            position_size=position_size,
            invalidation_level=stop_loss,
            order_blocks_used=order_blocks_used,
            flow_confirmation=flow_confirmation
        )

# ============================================================================
# RISK MANAGEMENT GATE
# ============================================================================

class RiskGate:
    """Enforces risk management rules before executing trades."""
    
    def __init__(self):
        self.daily_loss = 0
        self.daily_start_equity = TRADING_CONFIG['starting_capital']
        self.max_drawdown = 0
        self.consecutive_losses = defaultdict(int)
        self.paused_strategies = {}  # strategy_name -> resume_time
    
    def can_trade(
        self,
        signal: Signal,
        current_positions: List[PaperPosition],
        current_equity: float
    ) -> Tuple[bool, str]:
        """
        Check if signal passes risk gate.
        
        Returns: (can_trade, reason)
        """
        # Check 1: Max concurrent positions
        open_positions = [p for p in current_positions if p.status == 'open']
        if len(open_positions) >= TRADING_CONFIG['max_concurrent_positions']:
            return False, f"Max concurrent positions ({TRADING_CONFIG['max_concurrent_positions']}) reached"
        
        # Check 2: Max 1 position per symbol
        symbol_positions = [p for p in open_positions if p.symbol == signal.symbol]
        if len(symbol_positions) >= TRADING_CONFIG['max_positions_per_symbol']:
            return False, f"Max positions for {signal.symbol} already open"
        
        # Check 3: Daily loss limit
        capital = TRADING_CONFIG['starting_capital']
        daily_loss_limit = capital * (TRADING_CONFIG['max_daily_loss_pct'] / 100)
        if self.daily_loss > daily_loss_limit:
            return False, f"Daily loss limit (${daily_loss_limit:.2f}) exceeded"
        
        # Check 4: Drawdown limit
        drawdown = (self.daily_start_equity - current_equity) / self.daily_start_equity
        dd_limit = TRADING_CONFIG['max_drawdown_pct'] / 100
        if drawdown > dd_limit:
            return False, f"Drawdown limit ({TRADING_CONFIG['max_drawdown_pct']}%) exceeded"
        
        # Check 5: Strategy paused?
        now = time.time()
        if signal.strategy_name in self.paused_strategies:
            resume_time = self.paused_strategies[signal.strategy_name]
            if now < resume_time:
                return False, f"Strategy paused until {datetime.fromtimestamp(resume_time)}"
            else:
                # Resume time passed, unpause
                del self.paused_strategies[signal.strategy_name]
        
        # Check 6: Correlation check (simplified)
        # Don't go long on correlated assets simultaneously
        if signal.direction == 'LONG':
            for pos in open_positions:
                if pos.direction == 'SHORT':
                    # Simple correlation check: SOL/ETH are correlated
                    if {signal.symbol, pos.symbol} == {'SOL/USD', 'ETH/USD'}:
                        return False, "Opposite positions on correlated assets blocked"
        
        return True, "APPROVED"
    
    def record_trade_result(self, trade: PaperPosition):
        """Record result of closed trade for circuit breakers."""
        if trade.status in ['closed_sl', 'closed_time']:
            self.consecutive_losses[trade.strategy_name] += 1
            self.daily_loss += abs(trade.pnl)
            
            # Circuit breaker: 3 consecutive losses
            if self.consecutive_losses[trade.strategy_name] >= TRADING_CONFIG['consecutive_loss_threshold']:
                pause_until = time.time() + TRADING_CONFIG['strategy_pause_duration']
                self.paused_strategies[trade.strategy_name] = pause_until
                logger.warning(f"PAPER MODE - Circuit breaker: {trade.strategy_name} paused for 24h. "
                             f"Consecutive losses: {self.consecutive_losses[trade.strategy_name]}")
        else:
            # Reset consecutive loss counter on win
            self.consecutive_losses[trade.strategy_name] = 0
    
    def update_drawdown(self, current_equity: float):
        """Update max drawdown tracking."""
        drawdown = self.daily_start_equity - current_equity
        if drawdown > self.max_drawdown:
            self.max_drawdown = drawdown
    
    def reset_daily(self):
        """Reset daily metrics at end of day."""
        self.daily_loss = 0
        self.daily_start_equity = TRADING_CONFIG['starting_capital']
        self.max_drawdown = 0

# ============================================================================
# PAPER TRADING EXECUTION ENGINE
# ============================================================================

class PaperTradingEngine:
    """Simulates trade execution in paper mode."""
    
    def __init__(self):
        self.positions = []
        self.position_id_counter = 0
        self.starting_equity = TRADING_CONFIG['starting_capital']
        self.current_equity = self.starting_equity
        self.equity_history = [self.starting_equity]
        self.risk_gate = RiskGate()
        self.performance = defaultdict(lambda: {
            'trades': 0,
            'wins': 0,
            'losses': 0,
            'profit_factor': 0,
            'win_rate': 0,
            'max_drawdown': 0,
            'total_pnl': 0
        })
    
    def execute_signal(self, signal: Signal) -> Optional[PaperPosition]:
        """
        Execute a signal as a paper trade.
        
        Returns: PaperPosition if opened, None if rejected
        """
        can_trade, reason = self.risk_gate.can_trade(signal, self.positions, self.current_equity)
        
        if not can_trade:
            alert = {
                'timestamp': signal.timestamp.isoformat(),
                'type': 'signal_rejected',
                'symbol': signal.symbol,
                'strategy': signal.strategy_name,
                'reason': reason
            }
            self._write_alert(alert)
            logger.info(f"PAPER MODE - Signal rejected: {signal.symbol} {signal.direction} - {reason}")
            return None
        
        # Create paper position
        self.position_id_counter += 1
        position = PaperPosition(
            position_id=f"POS_{self.position_id_counter:05d}",
            symbol=signal.symbol,
            timeframe=signal.timeframe,
            strategy_name=signal.strategy_name,
            direction=signal.direction,
            entry_price=signal.entry_price,
            entry_time=signal.timestamp,
            stop_loss=signal.stop_loss,
            take_profit=signal.take_profit,
            position_size=signal.position_size,
            risk_amount=signal.risk_amount,
            pnl=0,
            pnl_pct=0,
            status='open',
            close_time=None,
            close_price=None,
            close_reason='',
            candles_held=0
        )
        
        self.positions.append(position)
        
        # Log trade opening
        alert = {
            'timestamp': signal.timestamp.isoformat(),
            'type': 'trade_opened',
            'position_id': position.position_id,
            'symbol': signal.symbol,
            'timeframe': signal.timeframe,
            'strategy': signal.strategy_name,
            'direction': signal.direction,
            'entry_price': signal.entry_price,
            'stop_loss': signal.stop_loss,
            'take_profit': signal.take_profit,
            'position_size': signal.position_size,
            'confidence_score': signal.confidence_score,
        }
        self._write_alert(alert)
        logger.info(f"PAPER MODE - Trade opened: {position.position_id} "
                   f"{signal.symbol} {signal.direction} @ {signal.entry_price:.2f}")
        
        return position
    
    def update_positions(self, price_updates: Dict[str, float]) -> List[PaperPosition]:
        """
        Update open positions with latest prices.
        Check for SL/TP hits.
        
        price_updates: {symbol: current_price}
        """
        closed_positions = []
        
        for position in self.positions:
            if position.status != 'open':
                continue
            
            if position.symbol not in price_updates:
                continue
            
            current_price = price_updates[position.symbol]
            position.candles_held += 1
            
            # Check stop loss
            if position.direction == 'LONG' and current_price <= position.stop_loss:
                self._close_position(position, current_price, 'SL', 'closed_sl')
                closed_positions.append(position)
                continue
            
            if position.direction == 'SHORT' and current_price >= position.stop_loss:
                self._close_position(position, current_price, 'SL', 'closed_sl')
                closed_positions.append(position)
                continue
            
            # Check take profit
            if position.direction == 'LONG' and current_price >= position.take_profit:
                self._close_position(position, current_price, 'TP', 'closed_tp')
                closed_positions.append(position)
                continue
            
            if position.direction == 'SHORT' and current_price <= position.take_profit:
                self._close_position(position, current_price, 'TP', 'closed_tp')
                closed_positions.append(position)
                continue
            
            # Time stop: close after N candles
            time_stop_candles = 50
            if position.candles_held >= time_stop_candles:
                self._close_position(position, current_price, 'TIME', 'closed_time')
                closed_positions.append(position)
        
        # Update equity
        self._update_equity()
        
        return closed_positions
    
    def _close_position(
        self,
        position: PaperPosition,
        close_price: float,
        reason_short: str,  # 'SL', 'TP', 'TIME'
        status: str
    ):
        """Close a position and calculate PnL."""
        position.close_price = close_price
        position.close_time = datetime.now()
        position.status = status
        
        if position.direction == 'LONG':
            pnl = (close_price - position.entry_price) * position.position_size
        else:  # SHORT
            pnl = (position.entry_price - close_price) * position.position_size
        
        position.pnl = pnl
        position.pnl_pct = (pnl / position.risk_amount * 100) if position.risk_amount > 0 else 0
        
        # Record for circuit breaker
        self.risk_gate.record_trade_result(position)
        
        # Update performance
        self.performance[position.strategy_name]['trades'] += 1
        if pnl > 0:
            self.performance[position.strategy_name]['wins'] += 1
        else:
            self.performance[position.strategy_name]['losses'] += 1
        
        # Log closure
        alert = {
            'timestamp': position.close_time.isoformat(),
            'type': f'trade_closed_{reason_short.lower()}',
            'position_id': position.position_id,
            'symbol': position.symbol,
            'strategy': position.strategy_name,
            'direction': position.direction,
            'entry_price': position.entry_price,
            'close_price': close_price,
            'pnl': pnl,
            'pnl_pct': position.pnl_pct,
            'candles_held': position.candles_held,
        }
        self._write_alert(alert)
        logger.info(f"PAPER MODE - Trade closed {reason_short}: {position.position_id} "
                   f"{position.symbol} PnL: ${pnl:.2f} ({position.pnl_pct:.1f}%)")
    
    def _update_equity(self):
        """Calculate current equity from open and closed positions."""
        equity = self.starting_equity
        
        # Add PnL from closed positions
        for position in self.positions:
            if position.status.startswith('closed'):
                equity += position.pnl
        
        self.current_equity = equity
        self.equity_history.append(equity)
        self.risk_gate.update_drawdown(equity)
    
    def _write_alert(self, alert: Dict[str, Any]):
        """Write alert to alerts.jsonl"""
        alert_file = ALERT_DIRS['alerts'] / 'alerts.jsonl'
        with open(alert_file, 'a') as f:
            f.write(json.dumps(alert) + '\n')
    
    def save_positions(self):
        """Save current positions to JSON."""
        positions_data = []
        for pos in self.positions:
            positions_data.append({
                'position_id': pos.position_id,
                'symbol': pos.symbol,
                'timeframe': pos.timeframe,
                'strategy_name': pos.strategy_name,
                'direction': pos.direction,
                'entry_price': pos.entry_price,
                'entry_time': pos.entry_time.isoformat(),
                'stop_loss': pos.stop_loss,
                'take_profit': pos.take_profit,
                'position_size': pos.position_size,
                'status': pos.status,
                'pnl': pos.pnl,
                'pnl_pct': pos.pnl_pct,
            })
        
        positions_file = ALERT_DIRS['positions'] / 'positions.json'
        with open(positions_file, 'w') as f:
            json.dump(positions_data, f, indent=2)
    
    def save_performance(self):
        """Save performance metrics to JSON."""
        perf_data = {}
        for strategy, metrics in self.performance.items():
            trades = metrics['trades']
            wins = metrics['wins']
            
            # Calculate metrics
            win_rate = (wins / trades * 100) if trades > 0 else 0
            
            perf_data[strategy] = {
                'trades': trades,
                'wins': wins,
                'losses': metrics['losses'],
                'win_rate': win_rate,
                'max_drawdown': metrics['max_drawdown'],
                'total_pnl': metrics['total_pnl'],
            }
        
        perf_file = ALERT_DIRS['performance'] / 'performance.json'
        with open(perf_file, 'w') as f:
            json.dump(perf_data, f, indent=2)

# ============================================================================
# DATA FETCHER (CCXT Integration)
# ============================================================================

class DataFetcher:
    """Fetches OHLCV data from exchange via ccxt."""
    
    def __init__(self, exchange_name: str = 'kraken'):
        self.exchange_name = exchange_name
        self.exchange = getattr(ccxt, exchange_name)()
        self.last_fetch_time = defaultdict(float)
    
    def fetch_ohlcv(
        self,
        symbol: str,
        timeframe: str,
        limit: int = 100
    ) -> Optional[pd.DataFrame]:
        """
        Fetch OHLCV data from exchange.
        
        Returns DataFrame or None if error
        """
        try:
            # Rate limit: minimum 5 seconds between fetches per symbol
            key = f"{symbol}_{timeframe}"
            time_since_last = time.time() - self.last_fetch_time[key]
            if time_since_last < 5:
                time.sleep(5 - time_since_last)
            
            candles = self.exchange.fetch_ohlcv(symbol, timeframe, limit=limit)
            
            df = pd.DataFrame(
                candles,
                columns=['timestamp', 'open', 'high', 'low', 'close', 'volume']
            )
            df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
            df.set_index('timestamp', inplace=True)
            
            self.last_fetch_time[key] = time.time()
            return df
            
        except Exception as e:
            logger.error(f"PAPER MODE - Error fetching {symbol} {timeframe}: {e}")
            return None
    
    def fetch_all_symbols(self) -> Dict[str, pd.DataFrame]:
        """Fetch data for all configured symbols."""
        data = {}
        
        for strategy, config in STRATEGIES_CONFIG.items():
            if not config['enabled']:
                continue
            
            symbol = config['symbol']
            timeframe = config['timeframe']
            
            df = self.fetch_ohlcv(symbol, timeframe, limit=config['lookback_candles'])
            if df is not None:
                data[symbol] = df
            else:
                logger.warning(f"PAPER MODE - Failed to fetch {symbol}")
        
        return data

# ============================================================================
# FLASK API SERVER
# ============================================================================

def create_flask_app(trading_engine: PaperTradingEngine, signal_history: deque):
    """Create Flask app for API endpoints."""
    app = Flask(__name__)
    
    @app.route('/health', methods=['GET'])
    def health():
        return jsonify({
            'status': 'healthy',
            'mode': 'PAPER',
            'timestamp': datetime.now().isoformat(),
            'current_equity': trading_engine.current_equity,
            'starting_equity': trading_engine.starting_equity,
        })
    
    @app.route('/strategies', methods=['GET'])
    def strategies():
        strategies_list = []
        for name, config in STRATEGIES_CONFIG.items():
            paused = name in trading_engine.risk_gate.paused_strategies
            strategies_list.append({
                'name': name,
                'symbol': config['symbol'],
                'timeframe': config['timeframe'],
                'enabled': config['enabled'],
                'paused': paused,
                'backtest_pf': config['profit_factor'],
                'backtest_wr': config['win_rate'],
            })
        return jsonify(strategies_list)
    
    @app.route('/signals', methods=['GET'])
    def signals():
        limit = request.args.get('limit', 20, type=int)
        signals_list = [
            {
                'timestamp': s.timestamp.isoformat(),
                'symbol': s.symbol,
                'timeframe': s.timeframe,
                'direction': s.direction,
                'entry_price': s.entry_price,
                'confidence_score': s.confidence_score,
                'strategy': s.strategy_name,
            }
            for s in list(signal_history)[-limit:]
        ]
        return jsonify(signals_list)
    
    @app.route('/positions', methods=['GET'])
    def positions():
        open_positions = [p for p in trading_engine.positions if p.status == 'open']
        positions_list = [
            {
                'position_id': p.position_id,
                'symbol': p.symbol,
                'direction': p.direction,
                'entry_price': p.entry_price,
                'stop_loss': p.stop_loss,
                'take_profit': p.take_profit,
                'entry_time': p.entry_time.isoformat(),
                'candles_held': p.candles_held,
            }
            for p in open_positions
        ]
        return jsonify(positions_list)
    
    @app.route('/performance', methods=['GET'])
    def performance():
        perf = {}
        for strategy, metrics in trading_engine.performance.items():
            trades = metrics['trades']
            wins = metrics['wins']
            perf[strategy] = {
                'trades': trades,
                'wins': wins,
                'losses': metrics['losses'],
                'win_rate': (wins / trades * 100) if trades > 0 else 0,
            }
        return jsonify(perf)
    
    @app.route('/comparison', methods=['GET'])
    def comparison():
        """Compare backtest vs paper results."""
        backtest_data = {
            'SOLUSD_4h': {'pf': 7.33, 'wr': 81.2},
            'ETHUSD_1h': {'pf': 10.58, 'wr': 76.9},
            'BTCUSD_4h': {'pf': 2.02, 'wr': 47.1},
        }
        
        comparison = {}
        for strategy, backtest_metrics in backtest_data.items():
            paper_metrics = trading_engine.performance.get(strategy, {})
            trades = paper_metrics.get('trades', 0)
            
            if trades == 0:
                deviation = None
            else:
                wins = paper_metrics.get('wins', 0)
                paper_wr = (wins / trades * 100) if trades > 0 else 0
                backtest_wr = backtest_metrics['wr']
                deviation = ((paper_wr - backtest_wr) / backtest_wr * 100)
            
            comparison[strategy] = {
                'backtest_wr': backtest_metrics['wr'],
                'paper_wr': (wins / trades * 100) if trades > 0 else 0,
                'deviation_pct': deviation,
                'alert': 'UNDERPERFORMING' if deviation and deviation < -20 else 'NORMAL'
            }
        
        return jsonify(comparison)
    
    @app.route('/alerts', methods=['GET'])
    def alerts():
        limit = request.args.get('limit', 50, type=int)
        alerts_file = ALERT_DIRS['alerts'] / 'alerts.jsonl'
        
        alerts_list = []
        if alerts_file.exists():
            with open(alerts_file, 'r') as f:
                for line in f:
                    try:
                        alerts_list.append(json.loads(line))
                    except:
                        pass
        
        return jsonify(alerts_list[-limit:])
    
    @app.route('/pause/<strategy>', methods=['POST'])
    def pause_strategy(strategy):
        if strategy in trading_engine.risk_gate.paused_strategies:
            return jsonify({'error': 'Already paused'}), 400
        
        pause_until = time.time() + 3600  # 1 hour
        trading_engine.risk_gate.paused_strategies[strategy] = pause_until
        logger.info(f"PAPER MODE - Strategy paused manually: {strategy}")
        return jsonify({'status': 'paused', 'resume_at': datetime.fromtimestamp(pause_until).isoformat()})
    
    @app.route('/resume/<strategy>', methods=['POST'])
    def resume_strategy(strategy):
        if strategy in trading_engine.risk_gate.paused_strategies:
            del trading_engine.risk_gate.paused_strategies[strategy]
        logger.info(f"PAPER MODE - Strategy resumed manually: {strategy}")
        return jsonify({'status': 'resumed'})
    
    @app.route('/kill', methods=['POST'])
    def kill():
        logger.warning("PAPER MODE - Emergency stop initiated")
        # In production, this would signal the main loop to shut down
        return jsonify({'status': 'emergency_stop'})

    @app.route('/inject', methods=['POST'])
    def inject_position():
        """Inject a forced paper position for pipeline validation."""
        try:
            data = request.get_json()
            if not data:
                return jsonify({'error': 'No JSON payload'}), 400

            required = ['symbol', 'direction', 'entry_price', 'stop_loss', 'take_profit']
            missing = [f for f in required if f not in data]
            if missing:
                return jsonify({'error': f'Missing fields: {missing}'}), 400

            import uuid
            pos_id = f"FORCE-{uuid.uuid4().hex[:8]}"
            now = datetime.utcnow()
            price = float(data['entry_price'])
            sl = float(data['stop_loss'])

            position = PaperPosition(
                position_id=pos_id,
                symbol=data['symbol'],
                timeframe=data.get('timeframe', '4h'),
                strategy_name=data.get('strategy_name', 'forced_validation'),
                direction=data['direction'],
                entry_price=price,
                entry_time=now,
                stop_loss=sl,
                take_profit=float(data['take_profit']),
                position_size=float(data.get('position_size', 1000.0)),
                risk_amount=abs(price - sl) * float(data.get('position_size', 1000.0)) / price,
                pnl=0.0,
                pnl_pct=0.0,
                status='open',
                close_time=None,
                close_price=None,
                close_reason='',
                candles_held=0
            )

            trading_engine.positions.append(position)
            logger.info(f"PAPER MODE - Injected forced position: {pos_id} {data['symbol']} {data['direction']}")

            return jsonify({
                'status': 'injected',
                'position_id': pos_id,
                'symbol': data['symbol'],
                'direction': data['direction'],
                'entry_price': price
            })
        except Exception as e:
            logger.error(f"Inject error: {e}")
            return jsonify({'error': str(e)}), 500

    return app

# ============================================================================
# MAIN SIGNAL ENGINE
# ============================================================================

class CryptoSignalEngine:
    """Main orchestrator for the signal engine."""
    
    def __init__(self):
        self.trading_engine = PaperTradingEngine()
        self.data_fetcher = DataFetcher()
        self.signal_generator = SignalGenerator()
        self.signal_history = deque(maxlen=1000)  # Keep last 1000 signals
        self.running = False
        self.flask_app = create_flask_app(self.trading_engine, self.signal_history)
    
    def run_cycle(self):
        """Single iteration of the main loop."""
        try:
            # Fetch latest data
            data = self.data_fetcher.fetch_all_symbols()
            
            if not data:
                logger.warning("PAPER MODE - No data fetched this cycle")
                return
            
            # Process each strategy
            for strategy_name, strategy_config in STRATEGIES_CONFIG.items():
                if not strategy_config['enabled']:
                    continue
                
                symbol = strategy_config['symbol']
                timeframe = strategy_config['timeframe']
                
                if symbol not in data:
                    continue
                
                df = data[symbol]
                
                # Generate signals
                signals = self.signal_generator.generate_signals(
                    symbol=symbol,
                    timeframe=timeframe,
                    df=df,
                    strategy_name=strategy_name
                )
                
                # Execute approved signals
                for signal in signals:
                    self.signal_history.append(signal)
                    position = self.trading_engine.execute_signal(signal)
                    
                    if position:
                        logger.info(f"PAPER MODE - Signal generated and executed: "
                                  f"{strategy_name} {signal.symbol} {signal.direction}")
            
            # Update positions with current prices
            price_updates = {symbol: df['close'].iloc[-1] for symbol, df in data.items()}
            closed_positions = self.trading_engine.update_positions(price_updates)
            
            for pos in closed_positions:
                logger.info(f"PAPER MODE - Position closed: {pos.position_id}")
            
            # Save state
            self.trading_engine.save_positions()
            self.trading_engine.save_performance()
            
            logger.info(f"PAPER MODE - Cycle complete. Equity: ${self.trading_engine.current_equity:.2f}")
            
        except Exception as e:
            logger.error(f"PAPER MODE - Error in main cycle: {e}", exc_info=True)
    
    def run_main_loop(self):
        """Main event loop."""
        logger.info("PAPER MODE - Signal engine starting...")
        self.running = True
        
        # Use weighted timing: 1h strategies every 60s, 4h strategies every 240s
        # For simplicity, we'll use 60s per cycle
        cycle_interval = 60
        
        while self.running:
            self.run_cycle()
            time.sleep(cycle_interval)
    
    def start_api_server(self):
        """Start Flask API in a separate thread."""
        def run_flask():
            logger.info("PAPER MODE - Flask API starting on port 8099")
            self.flask_app.run(host='0.0.0.0', port=8099, debug=False, threaded=True)
        
        flask_thread = threading.Thread(target=run_flask, daemon=True)
        flask_thread.start()
        logger.info("PAPER MODE - Flask API thread started")
    
    def start(self):
        """Start the signal engine."""
        logger.info("=" * 80)
        logger.info("PAPER MODE - GodsView Crypto Signal Engine Starting")
        logger.info(f"Starting Capital: ${TRADING_CONFIG['starting_capital']:,.2f}")
        logger.info(f"Mode: {TRADING_CONFIG['mode']}")
        logger.info("=" * 80)
        
        # Start API server
        self.start_api_server()
        
        # Run main loop
        try:
            self.run_main_loop()
        except KeyboardInterrupt:
            logger.info("PAPER MODE - Shutdown signal received")
            self.stop()
    
    def stop(self):
        """Stop the signal engine."""
        self.running = False
        logger.info("PAPER MODE - Signal engine stopped")

# ============================================================================
# ENTRY POINT
# ============================================================================

if __name__ == '__main__':
    engine = CryptoSignalEngine()
    engine.start()
